#!/bin/bash

# Strict mode
set -euo pipefail

#------------------------------------------------------------------------------
# Configuration Variables
#------------------------------------------------------------------------------
# Base directory where RabbitMQ was unpacked and renamed
# e.g., /app/layered/rabbitmq after unpacking and renaming
INSTALL_DIR="/app/layered/rabbitmq"

# Target user and group for running RabbitMQ (must exist - e.g., from Kerberos)
TARGET_USER="tmv_prod_rmq"
TARGET_GROUP="tmv_prod_rmqg"

# Desired nofile (ulimit -n) limit
NOFILE_LIMIT=100000

# Name for the systemd service
SERVICE_NAME="rabbitmq-server"

#------------------------------------------------------------------------------
# Helper Functions
#------------------------------------------------------------------------------
log_info() {
    echo "[INFO] $1"
}

log_error() {
    echo "[ERROR] $1" >&2
}

#------------------------------------------------------------------------------
# Pre-flight Checks
#------------------------------------------------------------------------------
log_info "Starting RabbitMQ post-installation configuration for $INSTALL_DIR"

# Check if running as root
if [[ "$(id -u)" -ne 0 ]]; then
   log_error "This script must be run as root or using sudo."
   exit 1
fi

# Verify installation directory exists
if [[ ! -d "$INSTALL_DIR" ]]; then
    log_error "Installation directory '$INSTALL_DIR' not found. Please unpack RabbitMQ first."
    exit 1
fi

# Verify target user exists
if ! id "$TARGET_USER" &>/dev/null; then
    log_error "Target user '$TARGET_USER' does not exist. Please ensure it's available via Kerberos/LDAP/SSSD."
    exit 1
else
    log_info "Target user '$TARGET_USER' found."
fi

# Verify target group exists
if ! getent group "$TARGET_GROUP" &>/dev/null; then
    log_error "Target group '$TARGET_GROUP' does not exist. Please ensure it's available via Kerberos/LDAP/SSSD."
    exit 1
else
    log_info "Target group '$TARGET_GROUP' found."
fi

#------------------------------------------------------------------------------
# Create Necessary Directories
#------------------------------------------------------------------------------
log_info "Creating RabbitMQ data and log directories..."
mkdir -p "$INSTALL_DIR/var/log/rabbitmq"
mkdir -p "$INSTALL_DIR/var/lib/rabbitmq/mnesia"
log_info "Directories created."

#------------------------------------------------------------------------------
# Create rabbitmq-env.conf
#------------------------------------------------------------------------------
log_info "Creating rabbitmq-env.conf..."
cat << EOF > "$INSTALL_DIR/etc/rabbitmq/rabbitmq-env.conf"
# Configuration generated by tmv_rabbitmq_postinstall.sh
# Base directory of the installation
BASE=$INSTALL_DIR

# Data and Log directories
NODENAME=rabbit@\${HOSTNAME}
NODE_IP_ADDRESS=127.0.0.1
MNESIA_BASE=\$BASE/var/lib/rabbitmq/mnesia
LOG_BASE=\$BASE/var/log/rabbitmq
EOF
log_info "rabbitmq-env.conf created."

#------------------------------------------------------------------------------
# Create systemd Service File
#------------------------------------------------------------------------------
log_info "Creating systemd service file /etc/systemd/system/$SERVICE_NAME.service ..."
cat << EOF > "/etc/systemd/system/$SERVICE_NAME.service"
[Unit]
Description=RabbitMQ Broker Service (TMV Custom Install)
After=network.target epmd@.socket
Wants=network.target epmd@.socket

[Service]
Type=notify
User=$TARGET_USER
Group=$TARGET_GROUP
WorkingDirectory=$INSTALL_DIR

ExecStart=$INSTALL_DIR/sbin/rabbitmq-server
ExecStop=$INSTALL_DIR/sbin/rabbitmqctl stop

NotifyAccess=all
TimeoutStartSec=3600
TimeoutStopSec=3600
Restart=on-failure
RestartSec=10
UMask=0027
# Set service limit (also set via limits.d)
LimitNOFILE=$NOFILE_LIMIT

[Install]
WantedBy=multi-user.target
EOF
log_info "Systemd service file created."

#------------------------------------------------------------------------------
# Create Logrotate Configuration
#------------------------------------------------------------------------------
log_info "Creating logrotate configuration /etc/logrotate.d/$SERVICE_NAME ..."
cat << EOF > "/etc/logrotate.d/$SERVICE_NAME"
$INSTALL_DIR/var/log/rabbitmq/*.log {
    weekly
    missingok
    rotate 7
    compress
    delaycompress
    notifempty
    # Run rabbitmqctl rotate_logs as the target user
    # This assumes su and the target user's shell environment work correctly
    postrotate
        if [ -f "$INSTALL_DIR/sbin/rabbitmqctl" ]; then
             su -s /bin/sh -c '$INSTALL_DIR/sbin/rabbitmqctl rotate_logs' $TARGET_USER > /dev/null 2>&1 || true
        fi
    endscript
}
EOF
log_info "Logrotate configuration created."

#------------------------------------------------------------------------------
# Create Tmpfiles.d Configuration
#------------------------------------------------------------------------------
log_info "Creating tmpfiles.d configuration /etc/tmpfiles.d/$SERVICE_NAME.conf ..."
# This ensures the /run/rabbitmq dir is created with correct permissions if needed by plugins/core
cat << EOF > "/etc/tmpfiles.d/$SERVICE_NAME.conf"
# Type Path        Mode UID          GID          Age Argument
d /run/rabbitmq 0755 $TARGET_USER $TARGET_GROUP -   -
EOF
log_info "Tmpfiles.d configuration created."

#------------------------------------------------------------------------------
# Configure System Limits (ulimit)
#------------------------------------------------------------------------------
log_info "Configuring system limits for user '$TARGET_USER' in /etc/security/limits.d/ ..."
LIMITS_FILE="/etc/security/limits.d/99-tmv-rabbitmq.conf"
cat << EOF > "$LIMITS_FILE"
# Limits for RabbitMQ user ($TARGET_USER) set by tmv_rabbitmq_postinstall.sh
# See 'man limits.conf'
$TARGET_USER          soft    nofile  $NOFILE_LIMIT
$TARGET_USER          hard    nofile  $NOFILE_LIMIT
EOF
chmod 0644 "$LIMITS_FILE"
log_info "System limits configuration created in $LIMITS_FILE."
log_info "Note: A system reboot or user re-login might be required for these limits to fully apply outside the systemd service."

#------------------------------------------------------------------------------
# Set Ownership and Permissions
#------------------------------------------------------------------------------
log_info "Setting ownership for $INSTALL_DIR to $TARGET_USER:$TARGET_GROUP ..."
chown -R "$TARGET_USER:$TARGET_GROUP" "$INSTALL_DIR"
log_info "Ownership set."
# Note: You might need more granular permissions depending on security requirements.
# e.g., chmod 700 "$INSTALL_DIR/var/lib/rabbitmq/mnesia"

#------------------------------------------------------------------------------
# Systemd Configuration Reload and Service Enable
#------------------------------------------------------------------------------
log_info "Reloading systemd daemon configuration..."
systemctl daemon-reload
log_info "Enabling $SERVICE_NAME service to start on boot..."
systemctl enable "$SERVICE_NAME.service"
log_info "$SERVICE_NAME service enabled."

#------------------------------------------------------------------------------
# Completion Message
#------------------------------------------------------------------------------
log_info "-------------------------------------------------------"
log_info "RabbitMQ post-installation script completed successfully."
log_info "Next Steps:"
log_info "1. Ensure compatible Erlang version is installed."
log_info "2. Verify system limits configuration ('$LIMITS_FILE') and kernel limit ('sysctl fs.file-max')."
log_info "   (A reboot/re-login might be needed for limits outside the service context)."
log_info "3. Configure firewall rules to allow access to RabbitMQ ports (e.g., 5672, 15672)."
log_info "4. Manually start the service using: sudo systemctl start $SERVICE_NAME.service"
log_info "5. Check service status using: sudo systemctl status $SERVICE_NAME.service"
log_info "6. Review logs in $INSTALL_DIR/var/log/rabbitmq/"
log_info "-------------------------------------------------------"

exit 0 